version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432" # Mapeia a porta local para o container
    environment:
      POSTGRES_USER: postgres     # Substitua pelo nome de usuário desejado
      POSTGRES_PASSWORD: password # Substitua pela senha desejada
      POSTGRES_DB: postgres       # Nome do banco de dados inicial
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistência dos dados

volumes:
  postgres_data:
