from app.db.postgres import create_table
from app.models import Model

def create_permissions_table():
    try:
        create_table('permissions', {
            "name": "VARCHAR(100) PRIMARY KEY",
            "type": "VARCHAR(100) NOT NULL",
            "load_data": "BOOLEAN DEFAULT FALSE",
            "manage_users": "BOOLEAN DEFAULT FALSE",
            "external_db": "BOOLEAN DEFAULT FALSE"
        })
        perms = Model('permissions')
        perms.insert({
            "type": "user",
            "name": "admin",
            "load_data": "TRUE",
            "external_db": "TRUE",
            "manage_users": "TRUE",
        })
    except Exception as e:
        print(f'Could not create table "permission": {e}')
        return e



def create_users_table():
    try:
        create_table('users', {
            "id":  "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "permission": "VARCHAR(100) REFERENCES permissions(name) ON DELETE CASCADE",
            "name": "VARCHAR(100) NOT NULL",
            "email": "VARCHAR(100) UNIQUE NOT NULL",
            "password": "VARCHAR(100) UNIQUE NOT NULL",
            "salt": "VARCHAR(100) UNIQUE NOT NULL",
            "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
            "updated_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP "
        })
    except Exception as e:
        print(f'Could not create table "users": {e}')
        return e
    else:
        print(f"Created table:", 'users')

